spring.datasource.url=${DB_URL:jdbc:postgresql://db.pupaupwvdsvtcxbfregk.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:liga1pro_app}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
