spring.datasource.url=jdbc:mysql://localhost:3306/liga1_pro?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8080
spring.application.name=liga1pro
jwt.secret=liga1proSecretKey2024SuperSeguraParaJWT1234567890
jwt.expiration=86400000